### ISSUE TITLE
Installation, Unary operator expected in cygwin, quotes?

### ISSUE THREAD

**Issue by ErnWong** [c9/install#44]
Hi,
In the [if statement, line 58](https://github.com/c9/install/blob/master/install.sh#L58), should there be quotes around `$os`?

Because, when I reran `install-sdk.sh` in cygwin, I got:

```
$./scripts/install-sdk.sh
Already up-to-date.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10911  100 10911    0     0  12755      0 --:--:-- --:--:-- --:--:-- 13322
bash: line 58: [: !=: unary operator expected
Installing base packages. Use --help for more options
bash: line 58: [: !=: unary operator expected
:Installing Node v0.12.0

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

and Googling brought [this up](http://stackoverflow.com/a/22179435).

---

Somehow `install-sdk.sh` worked in cygwin the first time though. I got the output saved somewhere.

**Comment by nightwing** [comment]
Hi
Thank you for reporting this issue.
install.sh shouldn't be invoked on windows, there was a regression which is fixed by https://github.com/c9/core/commit/4c64c5245aa4248869bcb3c9298134d2e06224f8#diff-4b4140932aa09b9ff43e0024a639e337R96

But adding the quotes is a good idea anyway https://github.com/c9/install/commit/a0f4489697c9c9934eda45e2574f5c60cdf744bf

Please reopen if you still see any error when running install-sdk.sh
